// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function WireGuardConnect(arg1:main.WireGuardConfig):Promise<boolean>;

export function WireGuardDisconnect():Promise<boolean>;
